version: '3.8'
    services:
      fastapi:
        build: .
        ports:
          - "8080:8080"
        depends_on:
          - langserve
      langserve:
        build:
          context: ./app
          dockerfile: Dockerfile
        ports:
          - "8000:8000"
